---
- hosts: wordpress
  connection: local 
  vars:
    vm_name: web-vm-1
    firewall_ip: 210.140.162.140
  tasks:
    - name: sshのキーをクラウドに送信する
      local_action:
        module: cloudstack_sshkey
        name: bols@le-mac
        public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: 仮想マシンを作成する
      local_action:
        module: cloudstack_vm
        name: "{{ vm_name }}"
        hypervisor: VMware
        template: b2d2a4fa-d694-444b-b961-0a0f9d7fe0f3
        service_offering: light.S1
        ssh_key: bols@le-mac

    - name: httpを通過させるようファイヤーウォールの設定を修正
      local_action:
        module: cloudstack_fw
        ip_address: "{{ firewall_ip }}"
        start_port: 80
        end_port: 80
        cidr: 0.0.0.0/0

    - name: sshを通過させるようファイヤーウォールの設定を修正
      local_action:
        module: cloudstack_fw
        ip_address: "{{ firewall_ip }}"
        start_port: 22
        end_port: 22
        cidr: 0.0.0.0/0

    - name: ポートフォワーディング80-> web-vm-1:80
      local_action:
        module: cloudstack_pf
        ip_address: "{{ firewall_ip }}"
        vm: "{{ vm_name }}"
        public_port: 80
        private_port: 80

    - name: ポートフォワーディング22-> web-vm-1:22
      local_action:
        module: cloudstack_pf
        ip_address: "{{ firewall_ip }}"
        vm: "{{ vm_name }}"
        public_port: 22
        private_port: 22
