---
- hosts: localhost
  connection: local 
  vars:
    vm_name: wordpless-vm-1
    firewall_ip: 210.140.162.140
    key_name: bols@balalaika
  tasks:
    - name: sshのキーをクラウドに送信する
      local_action:
        module: cs_sshkeypair
        name: "{{ key_name }}"
        public_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: 仮想マシンを作成する
      local_action:
        module: cs_instance
        name: "{{ vm_name }}"
        hypervisor: VMware
        template: b2d2a4fa-d694-444b-b961-0a0f9d7fe0f3
        service_offering: light.S1
        ssh_key: "{{ key_name }}"

    - name: httpを通過させるようファイヤーウォールの設定を修正
      local_action:
        module: cs_firewall
        ip_address: "{{ firewall_ip }}"
        start_port: 80
        end_port: 80
        cidr: 0.0.0.0/0

    - name: sshを通過させるようファイヤーウォールの設定を修正
      local_action:
        module: cs_firewall
        ip_address: "{{ firewall_ip }}"
        start_port: 22
        end_port: 22
        cidr: 0.0.0.0/0

    - name: ポートフォワーディング80-> web-vm-1:80
      local_action:
        module: cs_portforward
        ip_address: "{{ firewall_ip }}"
        vm: "{{ vm_name }}"
        public_port: 80
        private_port: 80

    - name: ポートフォワーディング22-> web-vm-1:22
      local_action:
        module: cs_portforward
        ip_address: "{{ firewall_ip }}"
        vm: "{{ vm_name }}"
        public_port: 22
        private_port: 22
